AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  DomainName:
    Type: String
    Default: example.net

  RedirectTargetDomain:
    Type: String
    Default: www.example.net

Resources:

  SSL:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName

  RedirectBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          - RedirectRule:
              HostName: !Ref RedirectTargetDomain
              Protocol: https
              HttpRedirectCode: 301

  CloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases: [ !Ref DomainName ]
        Enabled: True
        HttpVersion: http2
        Origins:
          - DomainName: !Select
              - 1
              - !Split ["//", !GetAtt RedirectBucket.WebsiteURL]
            Id: origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: origin
          DefaultTTL: 5
          MaxTTL: 30
          Compress: true
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          AcmCertificateArn: !Ref SSL
          SslSupportMethod: sni-only
