AWSTemplateFormatVersion: "2010-09-09"

Parameters:

  DomainName:
    Type: String
    Default: www.example.net

Resources:

  SSL:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName

  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub "${DomainName}-logs"

  SiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
        RoutingRules:

          # Redirect article index to posts
          - RoutingRuleCondition:
              KeyPrefixEquals: articles.html
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts.html
              HttpRedirectCode: 301

          # Special rule to avoid a name clash
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2015/resolutions
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/2015-resolutions
              HttpRedirectCode: 301


          # Redirect remaining articles/20XX to posts/
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2020/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2019/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2018/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2017/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2016/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2015/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2014/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2013/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2010/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2008/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2007/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2006/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2005/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2004/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2002/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301
          - RoutingRuleCondition:
              KeyPrefixEquals: articles/2001/
            RedirectRule:
              HostName: !Ref DomainName
              ReplaceKeyPrefixWith: posts/
              HttpRedirectCode: 301

      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket

  CloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Enabled: True
        HttpVersion: http2
        Origins:
          - DomainName: !Select
              - 1
              - !Split ["//", !GetAtt SiteBucket.WebsiteURL]
            Id: origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: origin
          DefaultTTL: 5
          MaxTTL: 30
          Compress: true
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref SSL
          SslSupportMethod: sni-only
