role_arn: arn:aws:iam::122588848868:role/WwwHosting
template_path: templates/redir.yaml
parameters:
  DomainName: www.superloopy.io
  RedirectTargetDomain: www.brautaset.org
  HostedZoneId: !stack_output zone::HostedZoneId
